name: Run Python tests

on: [push, pull_request]

jobs:
    build:
        name: Run tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.9', '3.10', '3.11']

        steps:
            - uses: szenius/set-timezone@v1.1
              with:
                  timezoneLinux: 'America/Chicago'
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: pip install pytest pytest-md pytest-emoji
            - name: Install Deps 2
              run: pip install -r apps/processor/requirements.txt
            - name: Install Deps 3
              run: pip install -r apps/processor/requirements-dev.txt
            - uses: pavelzw/pytest-action@v2
              working-directory: apps/processor
              with:
                  emoji: true
                  verbose: false
                  job-summary: true
