name: Pytest

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.11'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r apps/processor/requirements.txt
                  pip install -r apps/processor/requirements-dev.txt

            - name: Run tests
              working-directory: apps/processor
              run: python3 -m pytest tests.py
